<template><div><h1 id="_4-基本操作指南" tabindex="-1"><a class="header-anchor" href="#_4-基本操作指南"><span>4. 基本操作指南</span></a></h1>
<p>SecRandom的核心功能是提供公平、公正、公开的随机选择机制。本章将详细介绍软件的基本操作流程，包括抽人功能和抽奖功能的完整使用方法，帮助您快速掌握软件的日常操作。</p>
<h2 id="_4-1-抽人功能" tabindex="-1"><a class="header-anchor" href="#_4-1-抽人功能"><span>4.1 抽人功能</span></a></h2>
<p>抽人功能适用于从指定人员名单中随机选择一个或多个人员的场景，如课堂点名、活动选人、随机分组等。以下是详细操作步骤：</p>
<h3 id="_4-1-1-准备工作" tabindex="-1"><a class="header-anchor" href="#_4-1-1-准备工作"><span>4.1.1 准备工作</span></a></h3>
<p>在使用抽人功能前，请确保已完成以下准备：</p>
<h4 id="_4-1-1-1-创建-导入名单" tabindex="-1"><a class="header-anchor" href="#_4-1-1-1-创建-导入名单"><span>4.1.1.1 创建/导入名单</span></a></h4>
<p>SecRandom支持多种方式管理抽人名单：</p>
<h5 id="创建新名单" tabindex="-1"><a class="header-anchor" href="#创建新名单"><span>创建新名单</span></a></h5>
<ol>
<li>在导航区点击「抽人」按钮，进入抽人模式界面</li>
<li>在左侧名单管理区，点击顶部下拉菜单，选择「新建名单」</li>
<li>在弹出的对话框中：
<ul>
<li>输入名单名称（如「班级名单」、「部门成员」等）</li>
<li>选择名单类型（普通名单/分组名单）</li>
<li>设置名单描述（可选）</li>
</ul>
</li>
<li>点击「确定」按钮，创建空白名单</li>
</ol>
<h5 id="手动添加人员" tabindex="-1"><a class="header-anchor" href="#手动添加人员"><span>手动添加人员</span></a></h5>
<ol>
<li>在空白名单界面，点击名单下方的「添加」按钮（➕图标）</li>
<li>在弹出的添加人员对话框中，填写信息：
<ul>
<li><strong>姓名</strong>：必填项，人员的全名</li>
<li><strong>编号</strong>：可选项，如学号、工号等</li>
<li><strong>部门/分组</strong>：可选项，用于分类</li>
<li><strong>备注</strong>：可选项，其他需要说明的信息</li>
</ul>
</li>
<li>点击「确认」按钮添加人员</li>
<li>重复步骤1-3添加更多人员</li>
<li>点击「保存」按钮保存名单</li>
</ol>
<h5 id="导入外部名单" tabindex="-1"><a class="header-anchor" href="#导入外部名单"><span>导入外部名单</span></a></h5>
<p>SecRandom支持从多种格式文件导入名单，避免手动输入的繁琐：</p>
<ol>
<li>在名单管理区点击「导入」按钮（📥图标）</li>
<li>在文件选择对话框中，选择要导入的文件：
<ul>
<li><strong>支持格式</strong>：CSV、TXT、Excel (XLSX)、JSON</li>
<li><strong>文件要求</strong>：
<ul>
<li>CSV/TXT文件：每行一个人员信息，字段用逗号分隔</li>
<li>Excel文件：第一行应为表头（姓名、编号等）</li>
<li>JSON文件：需符合指定格式</li>
</ul>
</li>
</ul>
</li>
<li>点击「打开」后，进入导入配置界面：
<ul>
<li>预览导入数据，确认字段匹配</li>
<li>选择需要导入的字段</li>
<li>设置重复数据处理方式（跳过/覆盖/提示）</li>
</ul>
</li>
<li>点击「完成导入」按钮，名单将自动加载到软件中</li>
</ol>
<blockquote>
<p><strong>提示</strong>：导入大名单（100人以上）时，软件会显示进度条，大型文件可能需要几秒钟处理时间。</p>
</blockquote>
<h5 id="从模板创建名单" tabindex="-1"><a class="header-anchor" href="#从模板创建名单"><span>从模板创建名单</span></a></h5>
<p>对于常见场景，软件提供预设模板快速创建名单：</p>
<ol>
<li>在「新建名单」对话框中，点击「从模板创建」选项卡</li>
<li>选择合适的模板类型：
<ul>
<li>学生名单模板（包含学号、姓名、班级等字段）</li>
<li>员工名单模板（包含工号、姓名、部门等字段）</li>
<li>会议签到模板（包含姓名、单位、职位等字段）</li>
</ul>
</li>
<li>选择模板后，名单将自动创建并包含预设字段</li>
</ol>
<h4 id="_4-1-1-2-名单管理操作" tabindex="-1"><a class="header-anchor" href="#_4-1-1-2-名单管理操作"><span>4.1.1.2 名单管理操作</span></a></h4>
<h5 id="查看名单详情" tabindex="-1"><a class="header-anchor" href="#查看名单详情"><span>查看名单详情</span></a></h5>
<ul>
<li>点击名单选择器下拉菜单，选择已保存的名单</li>
<li>名单列表将显示该名单的所有人员信息</li>
<li>可通过右侧滚动条浏览长名单</li>
<li>使用列表上方的搜索框快速查找特定人员</li>
</ul>
<h5 id="编辑名单" tabindex="-1"><a class="header-anchor" href="#编辑名单"><span>编辑名单</span></a></h5>
<ol>
<li>选择需要编辑的名单</li>
<li>点击名单管理区的「编辑」按钮（✏️图标）</li>
<li>可进行以下操作：
<ul>
<li><strong>修改人员信息</strong>：双击列表中的人员行进行编辑</li>
<li><strong>删除人员</strong>：选中人员后点击「删除」按钮（🗑️图标）</li>
<li><strong>调整顺序</strong>：拖动人员行调整顺序</li>
<li><strong>批量操作</strong>：按住Ctrl键多选，进行批量删除或分组</li>
</ul>
</li>
<li>完成编辑后点击「保存」按钮</li>
</ol>
<h5 id="名单分组管理" tabindex="-1"><a class="header-anchor" href="#名单分组管理"><span>名单分组管理</span></a></h5>
<p>对于包含大量人员的名单，可创建分组以便灵活抽取：</p>
<ol>
<li>在名单管理区点击「分组」按钮（📁图标）</li>
<li>在分组管理界面：
<ul>
<li>点击「创建分组」添加新分组</li>
<li>为分组命名（如「第一组」、「技术部」等）</li>
<li>将人员从左侧主名单拖动到右侧分组中</li>
<li>可创建多个分组，人员可属于多个分组</li>
</ul>
</li>
<li>点击「确定」保存分组设置</li>
<li>抽人时可选择从整个名单或特定分组中抽取</li>
</ol>
<h5 id="名单导出与分享" tabindex="-1"><a class="header-anchor" href="#名单导出与分享"><span>名单导出与分享</span></a></h5>
<ol>
<li>选择需要导出的名单</li>
<li>点击「导出」按钮（📤图标）</li>
<li>在导出对话框中：
<ul>
<li>选择导出格式（CSV、Excel、TXT、JSON）</li>
<li>设置导出字段</li>
<li>选择保存位置</li>
</ul>
</li>
<li>点击「导出」按钮完成操作</li>
<li>导出的名单文件可用于备份或分享给其他SecRandom用户</li>
</ol>
<h3 id="_4-1-2-抽人参数设置" tabindex="-1"><a class="header-anchor" href="#_4-1-2-抽人参数设置"><span>4.1.2 抽人参数设置</span></a></h3>
<p>在开始抽取前，可根据需求自定义多种抽取参数，以满足不同场景的需求：</p>
<h4 id="基本设置" tabindex="-1"><a class="header-anchor" href="#基本设置"><span>基本设置</span></a></h4>
<p>在抽人模式界面右侧的「抽取设置面板」中进行配置：</p>
<ul>
<li>
<p><strong>抽取人数</strong>：</p>
<ul>
<li>通过数字输入框或上下箭头设置</li>
<li>范围：1-100人</li>
<li>可直接输入数字或使用滑块调整</li>
<li>下方显示当前设置占总人数的百分比</li>
</ul>
</li>
<li>
<p><strong>抽取模式</strong>：</p>
<ul>
<li><strong>单次抽取</strong>：一次性抽取指定数量的人员</li>
<li><strong>连续抽取</strong>：逐个抽取，每次抽取1人，共抽取指定次数</li>
<li><strong>随机排序</strong>：将所有人员随机排序，不指定具体抽取人数</li>
<li><strong>分组抽取</strong>：按预设分组分别抽取指定人数</li>
</ul>
</li>
<li>
<p><strong>抽取范围</strong>：</p>
<ul>
<li><strong>全部人员</strong>：从当前名单所有人员中抽取</li>
<li><strong>指定分组</strong>：仅从 selected分组中抽取</li>
<li><strong>排除已抽</strong>：排除本次会话中已抽取过的人员</li>
<li><strong>自定义范围</strong>：手动选择参与抽取的人员</li>
</ul>
</li>
</ul>
<h4 id="高级设置" tabindex="-1"><a class="header-anchor" href="#高级设置"><span>高级设置</span></a></h4>
<p>点击「高级设置」展开更多选项：</p>
<ul>
<li>
<p><strong>动画效果</strong>：</p>
<ul>
<li><strong>滚动效果</strong>：名单快速滚动后停止在结果上</li>
<li><strong>闪烁效果</strong>：随机高亮闪烁人员，逐渐减速直至停止</li>
<li><strong>渐显效果</strong>：结果人员逐渐清晰显示</li>
<li><strong>无动画</strong>：直接显示结果，适合需要快速抽取的场景</li>
<li>可调节动画持续时间（1-5秒）</li>
</ul>
</li>
<li>
<p><strong>结果显示</strong>：</p>
<ul>
<li><strong>显示顺序</strong>：抽取顺序/姓名排序/编号排序</li>
<li><strong>显示信息</strong>：选择结果中显示的人员信息（姓名/编号/部门等）</li>
<li><strong>字体大小</strong>：调整结果显示文字大小</li>
<li><strong>背景样式</strong>：结果区域的背景效果（高亮/边框/无）</li>
</ul>
</li>
<li>
<p><strong>音效设置</strong>：</p>
<ul>
<li><strong>抽取开始提示音</strong>：开启/关闭</li>
<li><strong>抽取过程音效</strong>：开启/关闭</li>
<li><strong>结果揭晓音效</strong>：开启/关闭</li>
<li>可选择不同音效方案</li>
</ul>
</li>
<li>
<p><strong>防重复设置</strong>：</p>
<ul>
<li><strong>会话内防重复</strong>：同一抽取会话中不重复抽取同一人</li>
<li><strong>绝对防重复</strong>：无论何时都不重复抽取同一人（需手动重置）</li>
<li><strong>重复间隔</strong>：设置允许重复抽取的最短间隔次数</li>
</ul>
</li>
</ul>
<h3 id="_4-1-3-执行抽取操作" tabindex="-1"><a class="header-anchor" href="#_4-1-3-执行抽取操作"><span>4.1.3 执行抽取操作</span></a></h3>
<p>完成名单准备和参数设置后，即可开始抽取：</p>
<h4 id="单次抽取流程" tabindex="-1"><a class="header-anchor" href="#单次抽取流程"><span>单次抽取流程</span></a></h4>
<ol>
<li>确认已选择正确的名单和设置</li>
<li>点击主内容区中央的大型「开始抽取」按钮
<ul>
<li>按钮为蓝色圆形，位于界面醒目位置</li>
<li>悬停时会显示提示文字和轻微放大效果</li>
</ul>
</li>
<li>抽取过程中：
<ul>
<li>按钮文字变为「抽取中...」</li>
<li>根据选择的动画效果显示动态过程</li>
<li>状态栏显示当前进度</li>
</ul>
</li>
<li>抽取完成后：
<ul>
<li>动画停止，结果区域显示抽取名单</li>
<li>播放结果揭晓音效</li>
<li>右上角显示「抽取完成」提示</li>
<li>结果自动保存到历史记录</li>
</ul>
</li>
</ol>
<h4 id="连续抽取流程" tabindex="-1"><a class="header-anchor" href="#连续抽取流程"><span>连续抽取流程</span></a></h4>
<ol>
<li>在抽取模式中选择「连续抽取」</li>
<li>设置总抽取人数</li>
<li>点击「开始抽取」按钮</li>
<li>首次抽取结果显示后：
<ul>
<li>「开始抽取」按钮变为「抽取下一位」</li>
<li>已抽取人员会标记为灰色并移至结果区</li>
</ul>
</li>
<li>点击「抽取下一位」继续抽取</li>
<li>全部抽取完成后显示最终结果汇总</li>
</ol>
<h4 id="紧急停止抽取" tabindex="-1"><a class="header-anchor" href="#紧急停止抽取"><span>紧急停止抽取</span></a></h4>
<p>在抽取过程中如需中断：</p>
<ul>
<li>点击「停止」按钮（抽取过程中「开始抽取」按钮会变为红色「停止」按钮）</li>
<li>软件会显示当前已抽取结果（如有）</li>
<li>会询问是否保存部分结果</li>
<li>选择「是」则保存已抽取结果，选择「否」则完全取消本次抽取</li>
</ul>
<h3 id="_4-1-4-抽取结果处理" tabindex="-1"><a class="header-anchor" href="#_4-1-4-抽取结果处理"><span>4.1.4 抽取结果处理</span></a></h3>
<p>抽取完成后，可对结果进行多种操作：</p>
<h4 id="查看结果详情" tabindex="-1"><a class="header-anchor" href="#查看结果详情"><span>查看结果详情</span></a></h4>
<ul>
<li>结果显示在主内容区的「抽取结果」面板中</li>
<li>包含信息：序号（抽取顺序）、姓名、其他选择显示的字段</li>
<li>每个结果项显示为独立卡片或列表项</li>
<li>卡片背景色交替，便于区分</li>
</ul>
<h4 id="结果操作功能" tabindex="-1"><a class="header-anchor" href="#结果操作功能"><span>结果操作功能</span></a></h4>
<p>结果区域下方提供多种操作按钮：</p>
<ul>
<li>
<p><strong>复制结果</strong>：</p>
<ul>
<li>点击「复制」按钮（📋图标）</li>
<li>可选择复制格式：纯文本/表格/Markdown/HTML</li>
<li>复制后可粘贴到其他应用程序</li>
</ul>
</li>
<li>
<p><strong>导出结果</strong>：</p>
<ul>
<li>点击「导出」按钮（📤图标）</li>
<li>选择导出格式（TXT/CSV/Excel/PDF）</li>
<li>设置保存路径和文件名</li>
<li>导出文件包含完整结果信息和抽取时间</li>
</ul>
</li>
<li>
<p><strong>分享结果</strong>：</p>
<ul>
<li>点击「分享」按钮（📤图标）</li>
<li>选择分享方式：邮件/微信/QQ/链接</li>
<li>通过链接分享时可设置有效期</li>
</ul>
</li>
<li>
<p><strong>打印结果</strong>：</p>
<ul>
<li>点击「打印」按钮（🖨️图标）</li>
<li>打开打印预览界面</li>
<li>可设置打印份数、纸张方向等</li>
</ul>
</li>
<li>
<p><strong>重新抽取</strong>：</p>
<ul>
<li>点击「重新抽取」按钮（🔄图标）</li>
<li>保留当前设置，立即重新抽取</li>
<li>会询问是否覆盖当前结果</li>
</ul>
</li>
<li>
<p><strong>保存为模板</strong>：</p>
<ul>
<li>点击「保存设置」按钮（💾图标）</li>
<li>将当前抽取参数保存为模板</li>
<li>下次可直接调用该模板</li>
</ul>
</li>
</ul>
<h3 id="_4-1-5-典型应用场景" tabindex="-1"><a class="header-anchor" href="#_4-1-5-典型应用场景"><span>4.1.5 典型应用场景</span></a></h3>
<h4 id="课堂随机点名" tabindex="-1"><a class="header-anchor" href="#课堂随机点名"><span>课堂随机点名</span></a></h4>
<ol>
<li>创建包含学生姓名和学号的名单</li>
<li>设置抽取人数为1人</li>
<li>选择「单次抽取」模式</li>
<li>选择「滚动效果」动画</li>
<li>点击「开始抽取」，软件随机选择一名学生</li>
<li>抽取结果可显示在大屏幕上</li>
</ol>
<h4 id="活动抽奖选人" tabindex="-1"><a class="header-anchor" href="#活动抽奖选人"><span>活动抽奖选人</span></a></h4>
<ol>
<li>导入参与活动人员名单</li>
<li>设置抽取人数为5人</li>
<li>选择「连续抽取」模式</li>
<li>设置动画持续时间为3秒</li>
<li>开启抽取音效</li>
<li>依次抽取5名幸运参与者</li>
<li>导出结果用于后续颁奖</li>
</ol>
<h4 id="团队随机分组" tabindex="-1"><a class="header-anchor" href="#团队随机分组"><span>团队随机分组</span></a></h4>
<ol>
<li>创建包含所有成员的名单</li>
<li>设置抽取人数为总人数</li>
<li>选择「随机排序」模式</li>
<li>点击「开始抽取」获得随机顺序</li>
<li>根据排序结果依次分配到不同小组</li>
<li>可将分组结果导出并打印</li>
</ol>
<h4 id="投票前随机排序" tabindex="-1"><a class="header-anchor" href="#投票前随机排序"><span>投票前随机排序</span></a></h4>
<ol>
<li>导入候选人名单</li>
<li>选择「随机排序」模式</li>
<li>点击「开始抽取」获得随机顺序</li>
<li>该顺序可作为正式投票的候选人顺序</li>
<li>可导出排序结果作为凭证</li>
</ol>
<h3 id="_4-1-6-常见问题与解决方法" tabindex="-1"><a class="header-anchor" href="#_4-1-6-常见问题与解决方法"><span>4.1.6 常见问题与解决方法</span></a></h3>
<h4 id="名单导入失败" tabindex="-1"><a class="header-anchor" href="#名单导入失败"><span>名单导入失败</span></a></h4>
<ul>
<li><strong>原因</strong>：文件格式错误、字段不匹配、文件编码问题</li>
<li><strong>解决</strong>：
<ul>
<li>检查文件是否符合支持的格式要求</li>
<li>确保CSV/TXT文件使用正确的分隔符</li>
<li>尝试另存文件为UTF-8编码</li>
<li>简化文件名，避免特殊字符</li>
</ul>
</li>
</ul>
<h4 id="抽取结果重复" tabindex="-1"><a class="header-anchor" href="#抽取结果重复"><span>抽取结果重复</span></a></h4>
<ul>
<li><strong>原因</strong>：未启用防重复设置、防重复范围设置不当</li>
<li><strong>解决</strong>：
<ul>
<li>在高级设置中启用「会话内防重复」</li>
<li>如需完全避免重复，选择「绝对防重复」</li>
<li>点击「重置重复记录」可清除历史重复记录</li>
</ul>
</li>
</ul>
<h4 id="名单无法保存" tabindex="-1"><a class="header-anchor" href="#名单无法保存"><span>名单无法保存</span></a></h4>
<ul>
<li><strong>原因</strong>：名单名称重复、权限问题、存储空间不足</li>
<li><strong>解决</strong>：
<ul>
<li>更换不同的名单名称</li>
<li>检查软件数据目录权限</li>
<li>清理磁盘空间</li>
<li>尝试修复数据库（设置→维护→修复数据库）</li>
</ul>
</li>
</ul>
<h4 id="抽取动画卡顿" tabindex="-1"><a class="header-anchor" href="#抽取动画卡顿"><span>抽取动画卡顿</span></a></h4>
<ul>
<li><strong>原因</strong>：电脑配置较低、动画效果设置过复杂</li>
<li><strong>解决</strong>：
<ul>
<li>降低动画持续时间</li>
<li>选择更简单的动画效果</li>
<li>关闭音效减少系统资源占用</li>
<li>在设置中降低界面渲染质量</li>
</ul>
</li>
</ul>
<h2 id="_4-2-抽奖功能" tabindex="-1"><a class="header-anchor" href="#_4-2-抽奖功能"><span>4.2 抽奖功能</span></a></h2>
<p>抽奖功能适用于从设置好的奖品列表中随机抽取获奖者的场景，如会议抽奖、活动颁奖、节日抽奖等。相比抽人功能，抽奖功能增加了奖品管理、概率设置和多轮抽奖等特性。</p>
<h3 id="_4-2-1-奖品管理" tabindex="-1"><a class="header-anchor" href="#_4-2-1-奖品管理"><span>4.2.1 奖品管理</span></a></h3>
<p>使用抽奖功能前，需要先创建和管理奖品列表：</p>
<h4 id="创建奖品列表" tabindex="-1"><a class="header-anchor" href="#创建奖品列表"><span>创建奖品列表</span></a></h4>
<ol>
<li>在导航区点击「抽奖」按钮，进入抽奖模式界面</li>
<li>在左侧奖品管理区，点击「新建奖品列表」按钮</li>
<li>在弹出的对话框中：
<ul>
<li>输入奖品列表名称（如「年会抽奖」、「节日促销」等）</li>
<li>设置列表描述（可选）</li>
<li>选择奖品排序方式（默认/价值/概率）</li>
</ul>
</li>
<li>点击「确定」创建空白奖品列表</li>
</ol>
<h4 id="添加奖品" tabindex="-1"><a class="header-anchor" href="#添加奖品"><span>添加奖品</span></a></h4>
<ol>
<li>在空白奖品列表界面，点击「添加奖品」按钮（➕图标）</li>
<li>在添加奖品对话框中填写信息：
<ul>
<li><strong>奖品名称</strong>：必填项（如「iPhone 13」、「小米手环」等）</li>
<li><strong>奖品图片</strong>：可选项，点击上传图片</li>
<li><strong>数量</strong>：该奖品的总数量</li>
<li><strong>价值</strong>：奖品价值（用于排序和统计）</li>
<li><strong>中奖概率</strong>：可设置相对概率</li>
<li><strong>描述</strong>：奖品的详细说明（可选）</li>
<li><strong>备注</strong>：内部参考信息（可选）</li>
</ul>
</li>
<li>点击「确定」添加奖品</li>
<li>重复上述步骤添加更多奖品</li>
</ol>
<blockquote>
<p><strong>提示</strong>：添加多个奖品时，可使用「复制添加」功能（选中奖品后点击「复制」按钮）快速创建相似奖品。</p>
</blockquote>
<h4 id="奖品排序与分组" tabindex="-1"><a class="header-anchor" href="#奖品排序与分组"><span>奖品排序与分组</span></a></h4>
<ol>
<li><strong>手动排序</strong>：拖动奖品行可调整显示顺序</li>
<li><strong>自动排序</strong>：点击列表上方的排序按钮，可按以下方式排序：
<ul>
<li>按名称（A-Z或Z-A）</li>
<li>按价值（高到低或低到高）</li>
<li>按概率（高到低或低到高）</li>
<li>按数量（多到少或少到多）</li>
</ul>
</li>
<li><strong>奖品分组</strong>：
<ul>
<li>点击「创建奖品组」按钮</li>
<li>命名奖品组（如「一等奖」、「二等奖」等）</li>
<li>将奖品拖动到对应的组中</li>
<li>可设置每组的抽取顺序</li>
</ul>
</li>
</ol>
<h4 id="奖品编辑与管理" tabindex="-1"><a class="header-anchor" href="#奖品编辑与管理"><span>奖品编辑与管理</span></a></h4>
<ol>
<li><strong>编辑奖品</strong>：双击奖品行或选中后点击「编辑」按钮（✏️图标）</li>
<li><strong>删除奖品</strong>：选中奖品后点击「删除」按钮（🗑️图标）</li>
<li><strong>批量操作</strong>：按住Ctrl键选择多个奖品，进行批量编辑或删除</li>
<li><strong>导入导出</strong>：
<ul>
<li>点击「导入奖品」可从CSV/Excel文件导入奖品列表</li>
<li>点击「导出奖品」可将当前奖品列表保存为文件</li>
</ul>
</li>
<li><strong>复制奖品列表</strong>：点击「复制列表」按钮可快速创建当前列表的副本</li>
</ol>
<h3 id="_4-2-2-概率设置" tabindex="-1"><a class="header-anchor" href="#_4-2-2-概率设置"><span>4.2.2 概率设置</span></a></h3>
<p>抽奖功能的核心是概率设置，SecRandom提供多种灵活的概率配置方式：</p>
<h4 id="平均概率模式" tabindex="-1"><a class="header-anchor" href="#平均概率模式"><span>平均概率模式</span></a></h4>
<p>最简单的概率分配方式，所有奖品平分总中奖概率：</p>
<ol>
<li>在概率设置区选择「平均概率」</li>
<li>软件自动计算每个奖品的中奖概率：
<ul>
<li>公式：(1/奖品总数) × (奖品数量)</li>
<li>例如：5个奖品各1个，每个中奖概率为20%</li>
</ul>
</li>
<li>点击「应用」按钮确认设置</li>
</ol>
<h4 id="自定义概率模式" tabindex="-1"><a class="header-anchor" href="#自定义概率模式"><span>自定义概率模式</span></a></h4>
<p>允许手动设置每个奖品的相对中奖概率：</p>
<ol>
<li>在概率设置区选择「自定义概率」</li>
<li>每个奖品行将显示概率调整控件：
<ul>
<li><strong>滑块调节</strong>：拖动滑块设置相对概率（0-100）</li>
<li><strong>直接输入</strong>：点击概率值直接输入数字</li>
<li><strong>百分比模式</strong>：直接设置中奖百分比</li>
</ul>
</li>
<li>概率设置区顶部显示「概率总和」：
<ul>
<li>当选择「百分比模式」时，总和必须为100%</li>
<li>当选择「相对概率」时，总和可以是任意值，软件会自动计算比例</li>
</ul>
</li>
<li>可使用「自动分配」按钮快速分配剩余概率</li>
<li>点击「应用」保存设置</li>
</ol>
<blockquote>
<p><strong>提示</strong>：概率值越高，奖品被抽中的可能性越大。设置为0的奖品将不会被抽中。</p>
</blockquote>
<h4 id="权重概率模式" tabindex="-1"><a class="header-anchor" href="#权重概率模式"><span>权重概率模式</span></a></h4>
<p>基于奖品价值或其他因素自动计算概率：</p>
<ol>
<li>在概率设置区选择「权重概率」</li>
<li>选择权重依据：
<ul>
<li><strong>按价值权重</strong>：价值越高，概率越高</li>
<li><strong>按数量权重</strong>：数量越多，概率越高</li>
<li><strong>自定义权重</strong>：手动输入权重值</li>
</ul>
</li>
<li>设置权重曲线：
<ul>
<li>线性：概率与权重成正比</li>
<li>指数：放大高权重奖品的概率优势</li>
<li>对数：缩小高权重奖品的概率优势</li>
</ul>
</li>
<li>点击「计算概率」按钮，软件自动分配概率</li>
<li>可手动微调后点击「应用」</li>
</ol>
<h4 id="智能概率模式" tabindex="-1"><a class="header-anchor" href="#智能概率模式"><span>智能概率模式</span></a></h4>
<p>根据已抽奖结果动态调整后续概率，确保最终结果接近预期：</p>
<ol>
<li>在概率设置区选择「智能概率」</li>
<li>设置预期结果：
<ul>
<li>总体中奖率</li>
<li>各奖品的目标出现次数</li>
</ul>
</li>
<li>系统会在抽奖过程中动态调整概率：
<ul>
<li>已抽中次数少于预期的奖品，概率会提高</li>
<li>已抽中次数多于预期的奖品，概率会降低</li>
</ul>
</li>
<li>点击「应用」保存设置</li>
</ol>
<h3 id="_4-2-3-抽奖规则配置" tabindex="-1"><a class="header-anchor" href="#_4-2-3-抽奖规则配置"><span>4.2.3 抽奖规则配置</span></a></h3>
<p>抽奖功能提供丰富的规则设置，满足不同场景需求：</p>
<h4 id="基本抽奖规则" tabindex="-1"><a class="header-anchor" href="#基本抽奖规则"><span>基本抽奖规则</span></a></h4>
<p>在抽奖模式界面右侧的「抽奖设置」面板中配置：</p>
<ul>
<li>
<p><strong>抽奖轮次</strong>：</p>
<ul>
<li><strong>单轮抽奖</strong>：一次设置抽取所有奖品</li>
<li><strong>多轮抽奖</strong>：可设置多轮，每轮抽取不同奖品</li>
<li>可设置轮次名称（如「第一轮：幸运奖」、「第二轮：三等奖」等）</li>
</ul>
</li>
<li>
<p><strong>每轮抽取数量</strong>：</p>
<ul>
<li>设置每轮抽取的奖品数量</li>
<li>可设置固定数量或随机数量（如1-3个）</li>
<li>如奖品数量有限，会显示剩余可抽数量</li>
</ul>
</li>
<li>
<p><strong>抽奖模式</strong>：</p>
<ul>
<li><strong>普通模式</strong>：每次抽取一个奖品</li>
<li><strong>连环模式</strong>：一次抽取多个奖品，依次揭晓</li>
<li><strong>红包模式</strong>：同时抽取多个奖品，一起揭晓</li>
</ul>
</li>
<li>
<p><strong>参与限制</strong>：</p>
<ul>
<li><strong>无限制</strong>：同一参与者可多次中奖</li>
<li><strong>每人限中一次</strong>：同一参与者只能中一次奖</li>
<li><strong>每人限中n次</strong>：可自定义限制次数</li>
<li><strong>同名排除</strong>：排除姓名相同的参与者</li>
</ul>
</li>
</ul>
<h4 id="高级抽奖规则" tabindex="-1"><a class="header-anchor" href="#高级抽奖规则"><span>高级抽奖规则</span></a></h4>
<p>点击「高级规则」展开更多设置：</p>
<ul>
<li>
<p><strong>奖品释放规则</strong>：</p>
<ul>
<li><strong>顺序释放</strong>：按顺序抽取完一轮奖品后再开始下一轮</li>
<li><strong>随机释放</strong>：所有奖品混合在一起随机抽取</li>
<li><strong>分级释放</strong>：按奖品价值从低到高或从高到低抽取</li>
</ul>
</li>
<li>
<p><strong>结果显示设置</strong>：</p>
<ul>
<li><strong>显示中奖动画</strong>：开启/关闭</li>
<li><strong>显示概率变化</strong>：是否显示概率动态变化过程</li>
<li><strong>显示剩余数量</strong>：是否在抽奖过程中显示剩余奖品数量</li>
</ul>
</li>
<li>
<p><strong>抽奖控制设置</strong>：</p>
<ul>
<li><strong>手动停止</strong>：抽奖动画需手动点击停止</li>
<li><strong>自动停止</strong>：达到设定时间后自动停止</li>
<li><strong>速度控制</strong>：可调节抽奖动画速度</li>
</ul>
</li>
<li>
<p><strong>特殊规则</strong>：</p>
<ul>
<li><strong>必中规则</strong>：设置一定次数后必中特定奖品</li>
<li><strong>连中规则</strong>：设置是否允许连续抽中同一奖品</li>
<li><strong>间隔规则</strong>：设置同一奖品被抽中的最小间隔次数</li>
</ul>
</li>
</ul>
<h3 id="_4-2-4-执行抽奖操作" tabindex="-1"><a class="header-anchor" href="#_4-2-4-执行抽奖操作"><span>4.2.4 执行抽奖操作</span></a></h3>
<p>完成奖品设置和规则配置后，即可开始抽奖：</p>
<h4 id="单轮抽奖流程" tabindex="-1"><a class="header-anchor" href="#单轮抽奖流程"><span>单轮抽奖流程</span></a></h4>
<ol>
<li>确认已选择正确的奖品列表</li>
<li>设置当轮抽取奖品数量</li>
<li>点击中央的大型「开始抽奖」按钮
<ul>
<li>按钮为紫色圆形，位于界面中央</li>
<li>按钮文字为白色「开始抽奖」</li>
</ul>
</li>
<li>抽奖过程：
<ul>
<li>按钮变为「停止抽奖」</li>
<li>中央区域显示奖品快速滚动动画</li>
<li>可听到紧张的抽奖音效</li>
<li>状态栏显示抽奖进度</li>
</ul>
</li>
<li>停止抽奖：
<ul>
<li><strong>手动停止</strong>：点击「停止抽奖」按钮</li>
<li><strong>自动停止</strong>：达到设定时间后自动停止</li>
</ul>
</li>
<li>结果揭晓：
<ul>
<li>动画停止，显示中奖奖品</li>
<li>播放中奖音效</li>
<li>结果区域显示奖品信息</li>
<li>奖品列表中该奖品数量减少</li>
</ul>
</li>
</ol>
<h4 id="多轮抽奖流程" tabindex="-1"><a class="header-anchor" href="#多轮抽奖流程"><span>多轮抽奖流程</span></a></h4>
<ol>
<li>在抽奖规则中设置轮次数量和每轮奖品</li>
<li>点击「开始多轮抽奖」按钮</li>
<li>系统显示第一轮抽奖界面</li>
<li>完成第一轮抽奖后：
<ul>
<li>结果自动保存</li>
<li>界面显示「第一轮完成」</li>
<li>可选择「查看本轮详情」或「继续下一轮」</li>
</ul>
</li>
<li>重复上述步骤完成所有轮次</li>
<li>所有轮次完成后，显示「抽奖结束」和总结果统计</li>
</ol>
<h4 id="紧急暂停与恢复" tabindex="-1"><a class="header-anchor" href="#紧急暂停与恢复"><span>紧急暂停与恢复</span></a></h4>
<ol>
<li>抽奖过程中如需暂停，点击「暂停」按钮</li>
<li>动画暂停，界面显示「已暂停」</li>
<li>可选择：
<ul>
<li><strong>继续抽奖</strong>：从暂停处继续</li>
<li><strong>重新开始</strong>：放弃当前进度，重新开始本轮</li>
<li><strong>结束抽奖</strong>：结束当前轮次，保存已产生的结果</li>
</ul>
</li>
</ol>
<h3 id="_4-2-5-抽奖结果管理" tabindex="-1"><a class="header-anchor" href="#_4-2-5-抽奖结果管理"><span>4.2.5 抽奖结果管理</span></a></h3>
<p>抽奖完成后，可对结果进行多种操作和管理：</p>
<h4 id="查看结果" tabindex="-1"><a class="header-anchor" href="#查看结果"><span>查看结果</span></a></h4>
<ul>
<li>当前轮次结果显示在中央结果区域</li>
<li>已抽奖结果列表显示在右侧「中奖记录」区</li>
<li>每条记录包含：奖品名称、抽取时间、操作按钮</li>
<li>可点击「查看全部」查看完整结果列表</li>
</ul>
<h4 id="结果操作" tabindex="-1"><a class="header-anchor" href="#结果操作"><span>结果操作</span></a></h4>
<p>结果区域提供以下操作按钮：</p>
<ul>
<li>
<p><strong>添加获奖者信息</strong>：</p>
<ul>
<li>点击结果记录旁的「编辑」按钮</li>
<li>输入获奖者姓名、联系方式等信息</li>
<li>可上传获奖者照片（可选）</li>
<li>点击「保存」记录信息</li>
</ul>
</li>
<li>
<p><strong>导出结果</strong>：</p>
<ul>
<li>点击「导出结果」按钮（📤图标）</li>
<li>选择导出范围：当前轮次/所有轮次</li>
<li>选择导出格式：Excel/CSV/PDF/Word</li>
<li>设置保存路径和文件名</li>
<li>导出文件包含完整的奖品和获奖者信息</li>
</ul>
</li>
<li>
<p><strong>打印奖状</strong>：</p>
<ul>
<li>选中结果记录，点击「打印奖状」按钮</li>
<li>系统生成标准奖状格式</li>
<li>可预览并打印</li>
<li>支持自定义奖状模板</li>
</ul>
</li>
<li>
<p><strong>分享结果</strong>：</p>
<ul>
<li>点击「分享」按钮（📤图标）</li>
<li>选择分享方式：微信/QQ/邮件/链接</li>
<li>可选择分享范围：单条结果/当前轮次/所有结果</li>
</ul>
</li>
<li>
<p><strong>作废结果</strong>：</p>
<ul>
<li>选中错误的结果记录</li>
<li>点击「作废」按钮</li>
<li>系统会询问确认</li>
<li>作废后奖品数量会自动恢复</li>
<li>操作会被记录在日志中</li>
</ul>
</li>
</ul>
<h4 id="结果统计与分析" tabindex="-1"><a class="header-anchor" href="#结果统计与分析"><span>结果统计与分析</span></a></h4>
<ol>
<li>点击「统计分析」按钮查看抽奖数据统计</li>
<li>系统生成多种统计图表：
<ul>
<li>奖品分布饼图</li>
<li>中奖时间线图</li>
<li>概率与实际结果对比图</li>
</ul>
</li>
<li>统计数据包括：
<ul>
<li>总抽奖次数</li>
<li>各奖品中奖次数</li>
<li>中奖率统计</li>
<li>奖品价值统计</li>
</ul>
</li>
<li>可导出统计图表和数据报告</li>
</ol>
<h3 id="_4-2-6-典型应用场景" tabindex="-1"><a class="header-anchor" href="#_4-2-6-典型应用场景"><span>4.2.6 典型应用场景</span></a></h3>
<h4 id="企业年会抽奖" tabindex="-1"><a class="header-anchor" href="#企业年会抽奖"><span>企业年会抽奖</span></a></h4>
<ol>
<li>创建包含不同级别奖品的列表：
<ul>
<li>特等奖：1名（高端手机）</li>
<li>一等奖：3名（平板电脑）</li>
<li>二等奖：10名（智能手表）</li>
<li>三等奖：50名（购物卡）</li>
</ul>
</li>
<li>设置多轮抽奖，从三等奖开始到特等奖</li>
<li>每轮设置相应的抽取数量</li>
<li>选择「手动停止」模式，增加现场互动性</li>
<li>为重要奖项设置更长的动画时间</li>
<li>抽奖完成后导出完整结果，用于后续颁奖</li>
</ol>
<h4 id="店铺开业促销" tabindex="-1"><a class="header-anchor" href="#店铺开业促销"><span>店铺开业促销</span></a></h4>
<ol>
<li>创建简单的奖品列表：
<ul>
<li>一等奖：1名（免单1000元）</li>
<li>二等奖：5名（免单200元）</li>
<li>三等奖：20名（免单50元）</li>
<li>参与奖：若干（小礼品）</li>
</ul>
</li>
<li>设置参与限制：每人限中一次</li>
<li>选择「自动停止」模式，设置2秒自动停止</li>
<li>顾客依次上前抽奖，结果即时显示</li>
<li>使用「添加获奖者信息」功能记录顾客联系方式</li>
</ol>
<h4 id="线上直播抽奖" tabindex="-1"><a class="header-anchor" href="#线上直播抽奖"><span>线上直播抽奖</span></a></h4>
<ol>
<li>创建适合线上展示的奖品列表</li>
<li>开启「显示剩余数量」和「显示概率变化」</li>
<li>设置「红包模式」同时抽取多个奖品</li>
<li>抽奖过程中与观众互动，增加趣味性</li>
<li>使用「分享结果」功能将中奖信息实时分享</li>
<li>导出结果用于后续奖品发放</li>
</ol>
</div></template>


